spring.application.name=ms-gateway
server.port=${PORT:8080}

# Conexión dinámica a Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# ─── Rutas del API Gateway ────────────────────────────────────────────────────
# El prefijo lb:// indica que Eureka resolverá el nombre del servicio
# y el Gateway balanceará la carga entre instancias disponibles.

# 0 — Autenticación
spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

# 1 — Clientes
spring.cloud.gateway.server.webmvc.routes[1].id=ms-cliente
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-cliente
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/clientes/**

# 2 — Productos
spring.cloud.gateway.server.webmvc.routes[2].id=ms-producto
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-producto
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/productos/**

# 3 — Inventario
spring.cloud.gateway.server.webmvc.routes[3].id=ms-inventario
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ms-inventario
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/inventario/**

# 4 — Pedidos
spring.cloud.gateway.server.webmvc.routes[4].id=ms-pedido
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ms-pedido
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/pedidos/**

# 5 — Pagos
spring.cloud.gateway.server.webmvc.routes[5].id=ms-pago
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ms-pago
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/pagos/**

# 6 — Envíos
spring.cloud.gateway.server.webmvc.routes[6].id=ms-envio
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ms-envio
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/envios/**

# 7 — Notificaciones
spring.cloud.gateway.server.webmvc.routes[7].id=ms-notificacion
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://ms-notificacion
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/notificaciones/**

# 8 — Carrito de compras
spring.cloud.gateway.server.webmvc.routes[8].id=ms-carrito
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ms-carrito
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/carrito/**

# 9 — Promociones
spring.cloud.gateway.server.webmvc.routes[9].id=ms-promocion
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://ms-promocion
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/promociones/**

# 10 — Reseñas
spring.cloud.gateway.server.webmvc.routes[10].id=ms-resena
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://ms-resena
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/resenas/**
