spring.application.name=ms-gateway
spring.application.name=ms-gateway
server.port=8080

# Conexión dinámica a Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Ejemplo de enrutamiento dinámico con Load Balancer (lb://) para el futuro ms-producto
spring.cloud.gateway.mvc.routes.id=ms-producto
spring.cloud.gateway.mvc.routes.uri=lb://ms-producto
spring.cloud.gateway.mvc.routes.predicates=Path=/api/productos/**